vich_uploader:
    db_driver: orm

    mappings:
        photo:
            uri_prefix: '%app.path.photo%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            upload_destination: '%kernel.project_dir%/public/%app.path.photo%'